# path
export PATH="${PATH}:${HOME}/packages/bin"

# alias
alias lt='ls -lhrt'
alias shangban='nvinit ssh -auth=oidc'
alias shangban-no-browser='nvinit ssh -auth=oidc -use-device-code'

# ssh
if [ -z "$(pgrep ssh-agent)" ]; then
    rm -rf /tmp/ssh-*
    eval $(ssh-agent -s) > /dev/null
else
    export SSH_AGENT_PID=$(pgrep ssh-agent | head -1)
    export SSH_AUTH_SOCK=$(find /tmp/ssh-* -name agent.* | head -1)
fi
echo "SSH_AUTH_SOCK is ${SSH_AUTH_SOCK}"

# tmux
alias work='tmux a -t work || tmux new -s work'
alias play='tmux a -t play || tmux new -s play'
alias gogo1='tmux a -t gogo1 || tmux new -s gogo1'
alias gogo2='tmux a -t gogo2 || tmux new -s gogo2'
alias tile_h='tmux select-layout even-vertical'
alias tile_v='tmux select-layout even-horizontal'
alias tile_4='tmux select-layout tiled'

